import type { InterrogationExperienceDefinition } from '../../engine/interrogationDynamics';

// 플레이어에게 보이는 주제와 전술은 자유 질문의 판정 기준이 아니라,
// 어떤 심리적 행동을 시도했는지 명시하는 입력이다. 모델은 아래 공개 claim
// 중 현재 계약이 허용한 것만 자연어로 표현한다.
export const case2InterrogationExperience: InterrogationExperienceDefinition = {
  defaultTopicId: 'CONFESSION_CORE',
  defaultTacticId: 'ASK_DETAIL',
  stalledTurnLimit: 2,
  maxCounterQuestions: 3,
  initialPsychology: {
    trust: 38,
    pressure: 18,
    guard: 46,
    protectiveness: 52,
  },
  topics: [
    {
      id: 'CONFESSION_CORE',
      label: '자백 핵심',
      description: '누가 운전했고 왜 자수했는지 자백의 중심을 확인한다.',
      starterQuestion: '운전한 사람이 정말 본인이라는 말을 다시 확인합니까?',
      focusClaimIds: ['C_I_DROVE', 'C_TAKE_MY_WORD'],
      maxTurns: 5,
      noProgressLimit: 2,
    },
    {
      id: 'COLLISION_GEOMETRY',
      label: '충돌 방향',
      description: '오토바이의 진입 방향과 충돌 순간의 감각을 묻는다.',
      starterQuestion: '오토바이는 정확히 어느 방향에서 나타났습니까?',
      focusClaimIds: [
        'C_RIDER_RIGHT',
        'C_BEFORE_MIDNIGHT',
      ],
      maxTurns: 4,
      noProgressLimit: 2,
    },
    {
      id: 'POST_CRASH_ROUTE',
      label: '사고 뒤 동선',
      description: '충돌 직후부터 귀가할 때까지의 이동을 시간순으로 고정한다.',
      starterQuestion: '사고 뒤 집까지 어떤 길로 이동했습니까?',
      focusClaimIds: ['C_HOME_DIRECT'],
      maxTurns: 4,
      noProgressLimit: 2,
    },
    {
      id: 'RESTAURANT_ALIBI',
      label: '왕곱창·카드',
      description: '식당 체류, 음주, 카드 결제 시각을 하나의 동선으로 묶는다.',
      starterQuestion: '그날 왕곱창에서 누구와 언제까지 있었습니까?',
      focusClaimIds: [
        'C_RESTAURANT_PRESENT',
        'C_CARD_OWNERSHIP',
        'C_CARD_LEFT_BEHIND',
        'C_SOBER',
        'C_CCTV_TIME_WRONG',
      ],
      maxTurns: 6,
      noProgressLimit: 2,
    },
    {
      id: 'DRIVER_ERGONOMICS',
      label: '차량·운전석',
      description: '차량 명의와 평소 시트 위치를 실제 운전 가능성과 연결한다.',
      starterQuestion: '평소 운전석을 어느 위치에 맞추고 운전합니까?',
      focusClaimIds: [
        'C_CAR_OWNERSHIP',
        'C_SEAT_ALWAYS_FORWARD',
        'C_SEAT_MOVED_LATER',
      ],
      maxTurns: 5,
      noProgressLimit: 2,
    },
    {
      id: 'CALL_RELATION',
      label: '딸·통화',
      description: '김서연과의 관계, 사고 뒤 통화, 보호 반응을 살핀다.',
      starterQuestion: '김서연 씨와 23시 52분에 무슨 통화를 했습니까?',
      focusClaimIds: [
        'C_DAUGHTER_IDENTITY',
        'C_CALL_OCCURRED',
        'C_DAUGHTER_UNRELATED',
        'C_PROTECTS_SOMEONE',
      ],
      maxTurns: 6,
      noProgressLimit: 2,
    },
    {
      id: 'SCENE_MEMORY',
      label: '현장 기억',
      description: '실제 운전자라면 알 수밖에 없는 현장 경험을 확인한다.',
      starterQuestion: '충돌 직후 현장에서 가장 먼저 본 것이 무엇입니까?',
      focusClaimIds: ['C_MEMORY_BLANK'],
      maxTurns: 4,
      noProgressLimit: 2,
    },
    {
      id: 'STAKES_PROTECTION',
      label: '희생·보호',
      description: '면허와 생계를 버리면서까지 자백을 지키는 이유를 묻는다.',
      starterQuestion: '이 자백으로 잃게 될 것들을 알고도 철회하지 않겠습니까?',
      focusClaimIds: [
        'C_ACCEPTS_RUIN',
        'C_PROTECTS_SOMEONE',
        'C_TAKE_MY_WORD',
        'C_ASKS_ABOUT_CHILD',
      ],
      maxTurns: 5,
      noProgressLimit: 2,
    },
  ],
  claims: [
    { id: 'C_I_DROVE', topicId: 'CONFESSION_CORE', valueId: 'SELF' },
    { id: 'C_TAKE_MY_WORD', topicId: 'CONFESSION_CORE' },
    {
      id: 'C_RIDER_RIGHT',
      topicId: 'COLLISION_GEOMETRY',
      valueId: 'RIGHT',
    },
    { id: 'C_BEFORE_MIDNIGHT', topicId: 'COLLISION_GEOMETRY' },
    {
      id: 'C_HOME_DIRECT',
      topicId: 'POST_CRASH_ROUTE',
      valueId: 'HOME_DIRECT',
    },
    {
      id: 'C_RESTAURANT_PRESENT',
      topicId: 'RESTAURANT_ALIBI',
      valueId: 'RESTAURANT_PRESENT',
    },
    { id: 'C_CARD_OWNERSHIP', topicId: 'RESTAURANT_ALIBI' },
    { id: 'C_CARD_LEFT_BEHIND', topicId: 'RESTAURANT_ALIBI' },
    { id: 'C_SOBER', topicId: 'RESTAURANT_ALIBI' },
    { id: 'C_CCTV_TIME_WRONG', topicId: 'RESTAURANT_ALIBI' },
    { id: 'C_CAR_OWNERSHIP', topicId: 'DRIVER_ERGONOMICS' },
    { id: 'C_SEAT_ALWAYS_FORWARD', topicId: 'DRIVER_ERGONOMICS' },
    { id: 'C_SEAT_MOVED_LATER', topicId: 'DRIVER_ERGONOMICS' },
    { id: 'C_DAUGHTER_IDENTITY', topicId: 'CALL_RELATION' },
    { id: 'C_CALL_OCCURRED', topicId: 'CALL_RELATION' },
    { id: 'C_DAUGHTER_UNRELATED', topicId: 'CALL_RELATION' },
    { id: 'C_PROTECTS_SOMEONE', topicId: 'CALL_RELATION' },
    { id: 'C_MEMORY_BLANK', topicId: 'SCENE_MEMORY' },
    { id: 'C_ACCEPTS_RUIN', topicId: 'STAKES_PROTECTION' },
    { id: 'C_ASKS_ABOUT_CHILD', topicId: 'STAKES_PROTECTION' },
  ],
  counterQuestionRules: [
    {
      id: 'CQ_DAUGHTER_BOUNDARY',
      question: '제 딸이라는 이유만으로 그 아이를 이 사고에 끌어들이실 겁니까?',
      topicIds: ['CALL_RELATION'],
      tacticIds: ['PRESSURE', 'PROBE'],
      minimumTopicTurns: 1,
      minimumProtectiveness: 55,
    },
    {
      id: 'CQ_CARD_LOGIC',
      question:
        '제 카드가 그 시각 결제됐다는 사실만으로 제가 운전하지 않았다고 단정하시는 겁니까?',
      topicIds: ['RESTAURANT_ALIBI'],
      tacticIds: ['PIN_STATEMENT', 'PRESSURE'],
      minimumTopicTurns: 1,
      minimumGuard: 50,
    },
    {
      id: 'CQ_CONFESSION_WEIGHT',
      question:
        '제가 제 발로 와서 서명까지 했는데, 왜 제 말은 처음부터 거짓이라고 보십니까?',
      topicIds: ['CONFESSION_CORE'],
      tacticIds: ['PIN_STATEMENT', 'PRESSURE'],
      minimumTopicTurns: 2,
      minimumGuard: 50,
    },
    {
      id: 'CQ_MEMORY_STANDARD',
      question: '충격을 받은 사람이 현장의 모든 걸 정확히 기억해야 합니까?',
      topicIds: ['SCENE_MEMORY'],
      tacticIds: ['PRESSURE', 'PROBE'],
      minimumTopicTurns: 2,
      minimumPressure: 28,
    },
    {
      id: 'CQ_STALL',
      question: '같은 질문을 반복해서 무엇을 얻으려는 겁니까?',
      minimumTopicTurns: 2,
      minimumConsecutiveNoProgressTurns: 2,
    },
  ],
  counterQuestionReplies: [
    {
      id: 'REPLY_PRINCIPLE',
      label: '원칙으로 답한다',
      text: '자백도 다른 증거와 똑같이 검증해야 합니다. 기록과 맞는지 확인하는 겁니다.',
      tacticId: 'ASK_DETAIL',
    },
    {
      id: 'REPLY_PRESS',
      label: '의도를 찌른다',
      text: '당신이 사실보다 누군가를 보호하는 일을 우선한다고 보기 때문입니다.',
      tacticId: 'PRESSURE',
    },
    {
      id: 'REPLY_EMPATHY',
      label: '마음을 인정한다',
      text: '제가 성급히 단정한다고 느끼는 건 이해합니다. 그래도 확인되는 기록은 함께 따져야 합니다.',
      tacticId: 'EMPATHIZE',
    },
    {
      id: 'REPLY_SILENCE',
      label: '대답하지 않는다',
      text: '(대답하지 않고 김만철이 다시 입을 열 때까지 기다린다.)',
      tacticId: 'SILENCE',
    },
  ],
};
